##File appender with HTMLLayout
#rootLogger.level = debug
#rootLogger.appenderRefs = R
#rootLogger.appenderRef.R.ref = File
#appender.File.type = File
#appender.File.name = File
#appender.File.fileName = app_log.html
#appender.File.append = true
#appender.File.layout.type = HtmlLayout 


#it is log4j1.x syntax
#log4j.rootLogger = DEBUG,R
#log4j.appender.R = org.apache.log4j.FileAppender
#log4j.appender.R.File = info.html
#log4j.appender.R.append = true
#log4j.appender.R.layout = org.apache.log4j.HTMLLayout

#status = error
#name = PropertiesConfig
#
#rootLogger.level = debug
#rootLogger.appenderRefs = file
#rootLogger.appenderRef.file.ref = FILE
#
#appender.FILE.type = File
#appender.FILE.name = FILE
#appender.FILE.fileName = app_log.html
#appender.FILE.append = true                            #Every time app runs, add logs to existing file instead of overwriting it.
#
#appender.FILE.layout.type = HtmlLayout
#appender.FILE.layout.title = Application Log
#appender.FILE.layout.locationInfo = true


status = error
name = XMLConfig

# -----------------------
# Root Logger
# -----------------------
rootLogger.level = debug
rootLogger.appenderRefs = xml
rootLogger.appenderRef.xml.ref = XML_FILE

# -----------------------
# XML File Appender
# -----------------------
appender.XML_FILE.type = File
appender.XML_FILE.name = XML_FILE
appender.XML_FILE.fileName = application_log.xml
appender.XML_FILE.append = true

# -----------------------
# Layout - XML Layout
# -----------------------
appender.XML_FILE.layout.type = XMLLayout
appender.XML_FILE.layout.compact = true
appender.XML_FILE.layout.locationInfo = true
appender.XML_FILE.layout.complete = true

